### ISSUE TITLE
Week 4 finally ready

### ISSUE THREAD

**Issue by hmkurth** [hmkurth/CommunityFoodResources#2]
@paulawaite 
What were your key learning points/takeaways?
Hibernate is pretty awesome, it seems like a great tool, but lots and lots to learn.
What challenged you?
I had a real challenge getting going on this part, I started at least 3 times and I just couldn't get it done.  
What problems did you solve and what resources did you use to solve them?
I ran into a few issues i had to research, alot of it by rewatching the videos and checking slack, a little googling about source release version problems...
More details in journal.txt

**Comment by hmkurth** [comment]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
First! Congrats again on the news interview!  I'm so impressed that you thought to reach out to them!  

Have you heard of and considered the [Madison College Challenge](https://madisoncollege.edu/madison-college-challenge)?  There is an [info session](https://www.eventbrite.com/e/madison-college-challenge-info-session-webinar-tickets-136648472259) next week. 

Nice job adding hibernate into your project right away, @hmkurth!  Your work looks good so far!

Something to consider and implement in the near future:
- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using that equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));` so that you don't have to compare each instance var/column manually like this: https://github.com/hmkurth/CommunityFoodResources/blob/9a15c6b1e48eda9b5f020b9a7709ddbabe602548/src/test/java/com/hmkurth/persistence/UserDaoTest.java#L111-L115
